# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: habit_tracker_development

test:
  <<: *default
  database: habit_tracker_test

production:
  primary: &primary_production
    <<: *default
    database: habit_tracker_production
    username: <%= ENV.fetch("DB_USERNAME", "habit_tracker") %>
    password: <%= ENV.fetch("HABIT_TRACKER_DATABASE_PASSWORD", "") %>
  cache:
    <<: *primary_production
    database: habit_tracker_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: habit_tracker_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: habit_tracker_production_cable
    migrations_paths: db/cable_migrate
